# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Tytu\u0142')),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
            options={
                'verbose_name': 'Tytul gazety',
                'verbose_name_plural': 'Tytuly gazet',
            },
        ),
    ]
