# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statystyka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partia',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Nazwa')),
                ('fullname', models.CharField(blank=True, max_length=50, verbose_name='Pe\u0142na nazwa')),
            ],
            options={
                'verbose_name': 'Ugrupowanie',
            },
        ),
        migrations.RemoveField(
            model_name='press',
            name='date',
        ),
        migrations.AddField(
            model_name='press',
            name='owner',
            field=models.CharField(blank=True, max_length=50, verbose_name='Wydawca'),
        ),
    ]
