# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-28 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_tournament_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='points',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rating',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=4),
        ),
    ]
