# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-30 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20170728_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
