# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-30 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_auto_20170730_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
