# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-04 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_auto_20170730_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='rating',
        ),
    ]
