# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-04 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_remove_tournament_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='base_rating',
            field=models.DecimalField(decimal_places=2, default='0.001', editable=False, max_digits=6),
        ),
    ]
