# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-04 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0015_auto_20170804_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='points',
            field=models.FloatField(default='1000.0'),
        ),
    ]
