# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-04 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0017_auto_20170804_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overallstandings',
            options={'verbose_name': 'Ranking', 'verbose_name_plural': 'Rankingi'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Gracz', 'verbose_name_plural': 'Gracze'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Turniej', 'verbose_name_plural': 'Turnieje'},
        ),
        migrations.AlterModelOptions(
            name='tournamentstandings',
            options={'verbose_name': 'Wyniki', 'verbose_name_plural': 'Wyniki'},
        ),
    ]
