# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-04 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0018_auto_20170804_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='overallstandings',
            name='player_points',
            field=models.FloatField(verbose_name='Liczba punkt\xf3w'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Imi\u0119'),
        ),
        migrations.AlterField(
            model_name='tournamentstandings',
            name='player_place',
            field=models.FloatField(verbose_name='Miejsce na turnieju'),
        ),
    ]
