# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-05 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0019_auto_20170804_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='player_num',
            field=models.IntegerField(verbose_name='Liczba graczy'),
        ),
    ]
