# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-25 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0021_auto_20170831_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OverallStandings',
        ),
    ]
