# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0024_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa armii')),
            ],
            options={
                'verbose_name': 'Armia',
                'verbose_name_plural': 'Armie',
            },
        ),
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='tournamentstandings',
            name='army',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.Army'),
        ),
    ]
