# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0026_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
    ]
