# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0028_auto_20171125_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstandings',
            name='killpoints',
            field=models.CharField(default='0', max_length=3, verbose_name='Kill points'),
        ),
        migrations.AddField(
            model_name='tournamentstandings',
            name='scenerypoints',
            field=models.CharField(default='0', max_length=3, verbose_name='Scenariusz'),
        ),
    ]
