# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0029_auto_20171204_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('title', models.CharField(default='Tytul', max_length=30, verbose_name='Tytu\u0142')),
                ('info', models.CharField(default='Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry...', max_length=245, verbose_name='Informacja')),
            ],
            options={
                'verbose_name': 'Linia czasu',
                'verbose_name_plural': 'Linie czasu',
            },
        ),
    ]
