# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0031_tournamentstandings_player_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentstandings',
            name='killpoints',
            field=models.CharField(default='0', max_length=9, verbose_name='Kill points'),
        ),
    ]
