# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0032_auto_20171207_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentstandings',
            name='player_points',
        ),
    ]
