# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0034_tournamentstandings_player_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentstandings',
            name='player_points',
        ),
    ]
