# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0036_tournamentstandings_player_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='rating',
            field=models.FloatField(blank=True, default=0, verbose_name='Rating'),
            preserve_default=False,
        ),
    ]
