# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0037_tournament_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentstandings',
            name='player_points',
        ),
    ]
