# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0040_remove_tournamentstandings_player_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstandings',
            name='player_points',
            field=models.FloatField(blank=True, default=1.0, verbose_name='Punkty'),
            preserve_default=False,
        ),
    ]
