# Generated by Django 2.0.5 on 2018-05-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warscrolls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warscroll',
            name='keywords',
        ),
        migrations.AddField(
            model_name='warscroll',
            name='keywords',
            field=models.ManyToManyField(to='warscrolls.Keyword'),
        ),
    ]
