# Generated by Django 2.0.5 on 2018-05-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warscrolls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warscroll',
            old_name='keywords',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=25),
        ),
    ]
