# Generated by Django 2.0.5 on 2018-05-17 11:18

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('calculator', '0042_news'),
        ('warscrolls', '0002_auto_20180517_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Warscroll',
            new_name='Scroll',
        ),
    ]
