# Generated by Django 2.0.5 on 2018-05-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warscrolls', '0003_auto_20180517_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scroll',
            name='army',
        ),
        migrations.RemoveField(
            model_name='scroll',
            name='key',
        ),
        migrations.DeleteModel(
            name='Scroll',
        ),
    ]
