# Generated by Django 2.0.5 on 2018-05-17 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0042_news'),
        ('warscrolls', '0004_auto_20180517_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.Army')),
                ('key', models.ManyToManyField(to='warscrolls.Keyword')),
            ],
            options={
                'verbose_name': 'Warscroll',
                'verbose_name_plural': 'Warscrolls',
            },
        ),
    ]
